config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
      resources :comments, only: [:create, :destroy, :update]
  end

  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 20}
    before_save :set_visit_count

    def update_visits_count
        self.update(visits_count: self.visits_count + 1)
    end

    private

    def set_visit_count
        self.visits_count ||= 0
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :set_article, except: [:index, :new, :create]

    #GET /articles
    def index
        @articles = Article.all
    end

    #GET /articles/:id
    def show
        @article.update_visits_count
        @comment = Comment.new
    end

    #GET /articles/new
    def new
        @article = Article.new
    end

    def edit
    end

    #POST /articles
    def create
        @article = current_user.articles.new(article_params)
        if @article.save
            redirect_to @article
        else
            render :new
        end
    end

    #DELETE /articles/:id
    def destroy
        #DELETE FROM articles
        @article.destroy # Destroy eliminar el objeto de la BD
        redirect_to articles_path
    end

    #PUT /articles/:id
    def update
        #UPDATE
        # @article.update_attributes({title: 'Nuevo titulo'})
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :authenticate_user!

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> artículo</h1>
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="be-red white top-space">
            * <%= message %>
        </div>
    <% end %>
    <div class="field">
        <%= f.text_field :title, placeholder: "Título del artículo", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :body, placeholder: "Escribe aquí el artículo", style:"height:250px;", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.submit "Guardar", class:"btn be-red white" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
    <%= render "form", name: "Editar" %>
<div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <h1><%= link_to article.title, article %></h1>
  <div>
    <%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class:"red" %>
  </div>
<% end %>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
    <h1>Crear artículo</h1>
    <%= form_for(@article) do |f| %>
        <% @article.errors.full_messages.each do |message| %>
            <div class="be-red white top-space">
                * <%= message %>
            </div>
        <% end %>
        <div class="field">
            <%= f.text_field :title, placeholder: "Título", class:"form-control" %>
        </div>
        <div class="field">
            <%= f.text_area :body, placeholder: "Escribe aquí el artículo", style:"height:250px;", class:"form-control" %>
        </div>
        <div class="field">
            <%= f.submit "Guardar", class:"btn be-red white" %>
        </div>
    <% end %>
<div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil? %>
<p>
  Escrito por: <%= @article.user.email %>
</p>
<% end %>
<p>
  Visitas: <%= @article.visits_count %>
</p>
<div>
  <%= @article.body %>
</div>

<diV class="field">
  <h3>Comentarios</h3>
  <%= render "comments/form" %>
  <ul id="comments-box">
    <% @article.comments.each do |comment| %>
      <li>
        <%= comment.body %> - <%= comment.user.email %>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <%= link_to "Editar", edit_article_path(@article) %>
</div>

app/views/comments/_form.html.erb
<%= form_for( [@article,@comment], remote: true, html: {id: "comments-form", :"data-type"=> "json" } ) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Tutorialrails</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/navigation" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/partials/_navigation.html.erb
<header>
  <nav class="be-red white large-padding">
    <ul class="no-list row center-xs middle-xs">
      <li class="col-md li-nav">
        <h1 class="no-margin" id="logo">Blog Rails</h1>
      </li>
      <li class="col-md li-nav">
        <%= link_to "Inicio", root_path %>
      </li>
      <li class="col-md li-nav">
        Diseño
      </li>
      <li class="col-md li-nav">
        Programación
      </li>
      <li class="col-md li-nav">
        Tecnología
      </li>
      <% if user_signed_in? %>
        <li class="col-md li-nav">
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
          <li class="col-md li-nav">
            <%= link_to "Iniciar sesión", new_user_session_path %>
          </li>
          <li class="col-md li-nav">
            <%= link_to "Crear cuenta", new_user_registration_path %>
          </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/welcome/index.html.erb
<h1>Bienvenido</h1>
<% if user_signed_in? %>
    <h2><%=  current_user.email %></h2>
<% end %>